### ISSUE TITLE
How to run tests after the command has exited?

### ISSUE THREAD

**Issue by tomekwi** [maxogden/tape-spawn#10]
I have a CLI program which writes some files. I want to [test these files](https://github.com/studio-b12/less-index/blob/0890766/test/bin/less-index.test.js#L95-L106) after my program has run – but before the test exits.

Using `spawnTest.end()` [fails](https://travis-ci.org/studio-b12/less-index/jobs/71977829#L292), because the tests are run after `t.end()`.

Is there a way to do it then?

**Comment by maxogden** [comment]
I dont fully understand your use case, but does the `end: false` argument help? https://github.com/maxogden/tape-spawn#var-spawntest--spawntapetest-commandstring-options

Example usage is here, I use `end: false` on the first tape-spawn so that it doesn't exit the test, that way I can do a second tape-spawn in the same test and wait for them both to finish and compare outputs before ending the test

https://github.com/maxogden/dat/blob/a4e01085781ba9f1a5f16f5be803b04d12a8c3a9/tests/push-pull-clone.js#L87

**Comment by tomekwi** [comment]
Here’s what I want:

1. Spawn a command
1. Run some tests with *tape-spawn*
1. Run some tests on the output which *tape-spawn* can’t cover
1. End the test

Here’s what *tape-spawn* does:

1. Spawn a command
1. Run some tests with *tape-spawn*
1. End the test
1. Run some tests on the output which *tape-spawn* can’t cover

Of course “Run some tests on the output…” fails because they are executed [after *tape-spawn* has called `t.end()`](https://travis-ci.org/studio-b12/less-index/jobs/71977829#L292-L297).

`end: false` helps, thanks. It still feels a bit like a workaround to me though. I thought the purpose of `spawnTest.end` was to do things after the spawned command has exited and before `t.end()`.
